document.querySelector('.menu')?.addEventListener('click',()=>document.querySelector('.nav')?.classList.toggle('open'));
function subscribe(e){e.preventDefault();const n=document.getElementById('form-note');if(n)n.textContent='Thanks — connect this form to your email provider before launch.';return false;}
(function(){['light-theme.css','lawyer-illustration.css','mobile.css','menu-mobile.css'].forEach(href=>{if(!document.querySelector('link[href="'+href+'"]')){const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.appendChild(l);}})})();
(function(){
const path=location.pathname.split('/').pop()||'index.html';
const data={
'deals.html':{label:'EDITORIAL · DEALS',image:'https://images.unsplash.com/photo-1554224155-bd4e04c3f2e6?auto=format&fit=crop&w=1800&q=85',alt:'Financial documents and calculator on a desk',caption:'Transactions examined through legal, financial and commercial lenses.'},
'private-equity.html':{label:'PRIVATE CAPITAL',image:'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=1800&q=85',alt:'Financial analysis and documents on a desk',caption:'Sponsor strategy, acquisition structures, leverage and the legal mechanics of private capital.'},
'financing.html':{label:'CAPITAL & FINANCING',image:'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1800&q=85',alt:'Financial documents and calculator on a desk',caption:'Debt, acquisition finance, capital structures and the financing decisions behind transactions.'},
'private-client.html':{label:'PRIVATE CLIENT',image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=85',alt:'Elegant private residence interior',caption:'Private client law, succession, wealth structuring and the legal issues that shape personal and family affairs.'},
'private-wealth.html':{label:'PRIVATE WEALTH',image:'https://images.unsplash.com/photo-1755307739588-0bf45e1e1ed6?auto=format&fit=crop&w=1800&q=85',alt:'Luxury yacht cruising on the ocean',caption:'Wealth preservation, investment structures, succession and the legal frameworks surrounding private capital.'},
'legal-tech.html':{label:'LEGAL TECHNOLOGY',image:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1800&q=85',alt:'Computer technology and circuitry',caption:'AI, legal technology, automation and the tools changing how lawyers research, review, draft and advise.'}
};
const d=data[path],main=document.querySelector('main.listing');if(!d||!main||main.querySelector('.section-hero'))return;
const style=document.createElement('style');style.textContent='.section-hero{width:100%;margin:34px 0 52px;border:2px solid #c9a35c;background:#fffdf8;box-sizing:border-box;overflow:hidden}.section-hero img{display:block;width:100%;height:360px;object-fit:cover}.section-hero-caption{padding:18px 22px 20px;border-top:1px solid #d5d0c5}.section-hero-caption span{font-size:10px;text-transform:uppercase;letter-spacing:.14em;color:#9a763d;font-weight:700}.section-hero-caption p{margin:7px 0 0;color:#596169;font-size:13px;line-height:1.55}.listing .list{margin-top:0}.listing .list article{border:1px solid #c9c4b9;background:#fffdf8;padding:30px;box-sizing:border-box}.listing .list article:hover{border-color:#c9a35c}@media(max-width:800px){.section-hero{margin:26px 0 38px}.section-hero img{height:240px}.section-hero-caption{padding:15px 17px 17px}.listing .list article{padding:23px}}';document.head.appendChild(style);
const hero=document.createElement('div');hero.className='section-hero';hero.innerHTML='<img src="'+d.image+'" alt="'+d.alt+'" loading="eager"><div class="section-hero-caption"><span>'+d.label+'</span><p>'+d.caption+'</p></div>';
const list=main.querySelector('.list');if(list)main.insertBefore(hero,list);
})();